name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  PHP_VERSION: '8.2'
  NODE_VERSION: '20'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ==================== CODE QUALITY ====================
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, ctype, json, pdo, pdo_mysql, redis, mongodb
          coverage: xdebug
          tools: composer:v2, phpcs, phpstan
      
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      
      - name: Install dependencies
        working-directory: ./Farm/backend
        run: composer install --prefer-dist --no-progress
      
      - name: Run PHPCS
        working-directory: ./Farm/backend
        run: composer run-script phpcs || true
      
      - name: Run PHPStan
        working-directory: ./Farm/backend
        run: composer run-script phpstan || true

  # ==================== SECURITY SCAN ====================
  security:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
      
      - name: Security Check
        working-directory: ./Farm/backend
        run: |
          composer audit || true
          
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'PHPFrarm'
          path: '.'
          format: 'HTML'
          
      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: reports/

  # ==================== UNIT TESTS ====================
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: phpfrarm_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root_password
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, ctype, json, pdo, pdo_mysql, redis, mongodb
          coverage: xdebug
          tools: composer:v2
      
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      
      - name: Install dependencies
        working-directory: ./Farm/backend
        run: composer install --prefer-dist --no-progress
      
      - name: Setup test environment
        working-directory: ./Farm/backend
        run: |
          cp .env.testing .env
          php artisan db:migrate --env=testing
          
      - name: Run Unit Tests
        working-directory: ./Farm/backend
        run: vendor/bin/phpunit --testsuite=Unit --coverage-clover coverage.xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./Farm/backend/coverage.xml
          flags: unit
          name: unit-tests

  # ==================== INTEGRATION TESTS ====================
  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: phpfrarm_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
      
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root_password
        ports:
          - 27017:27017
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, ctype, json, pdo, pdo_mysql, redis, mongodb
          tools: composer:v2
      
      - name: Install dependencies
        working-directory: ./Farm/backend
        run: composer install --prefer-dist --no-progress
      
      - name: Run Integration Tests
        working-directory: ./Farm/backend
        run: vendor/bin/phpunit --testsuite=Integration
      
      - name: Run API Tests
        working-directory: ./Farm/backend
        run: vendor/bin/phpunit --testsuite=API

  # ==================== SECURITY TESTS ====================
  test-security:
    name: Security Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, ctype, json, pdo, pdo_mysql
          tools: composer:v2
      
      - name: Install dependencies
        working-directory: ./Farm/backend
        run: composer install --prefer-dist --no-progress
      
      - name: Run Security Tests
        working-directory: ./Farm/backend
        run: vendor/bin/phpunit --testsuite=Security

  # ==================== FRONTEND BUILD ====================
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: Farm/frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./Farm/frontend
        run: npm ci
      
      - name: Lint frontend
        working-directory: ./Farm/frontend
        run: npm run lint || true
      
      - name: Build frontend
        working-directory: ./Farm/frontend
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: Farm/frontend/build/
          retention-days: 7

  # ==================== BUILD DOCKER IMAGES ====================
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [lint, test-unit, test-integration, build-frontend]
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Farm/backend
          file: ./Farm/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Farm/frontend
          file: ./Farm/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-frontend
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ==================== DEPLOY TO STAGING ====================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build-images]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.phpfrarm.com
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to ECS Staging
        run: |
          chmod +x ./infra/scripts/deploy.sh
          ./infra/scripts/deploy.sh staging
        env:
          CLUSTER_NAME: phpfrarm-staging
          SERVICE_NAME: phpfrarm-api
          IMAGE_TAG: ${{ github.sha }}
      
      - name: Run smoke tests
        run: |
          sleep 30
          curl -f https://staging.phpfrarm.com/health || exit 1
          curl -f https://staging.phpfrarm.com/health/ready || exit 1

  # ==================== DEPLOY TO PRODUCTION ====================
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-images, test-security]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://api.phpfrarm.com
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to ECS Production
        run: |
          chmod +x ./infra/scripts/deploy.sh
          ./infra/scripts/deploy.sh production
        env:
          CLUSTER_NAME: phpfrarm-production
          SERVICE_NAME: phpfrarm-api
          IMAGE_TAG: ${{ github.sha }}
          DEPLOYMENT_STRATEGY: blue-green
      
      - name: Run smoke tests
        run: |
          sleep 60
          curl -f https://api.phpfrarm.com/health || exit 1
          curl -f https://api.phpfrarm.com/health/ready || exit 1
      
      - name: Notify deployment
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Production deployment completed successfully'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        if: always()

  # ==================== ROLLBACK ====================
  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    if: failure()
    needs: [deploy-production]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Rollback production
        run: |
          chmod +x ./infra/scripts/rollback.sh
          ./infra/scripts/rollback.sh production
        env:
          CLUSTER_NAME: phpfrarm-production
          SERVICE_NAME: phpfrarm-api
