<?php

/**
 * Input Validation Configuration
 * 
 * Configure input validation rules for headers, query parameters,
 * and request bodies.
 * 
 * @package PHPFrarm
 */

return [
    /*
    |--------------------------------------------------------------------------
    | Enable Content-Type Enforcement
    |--------------------------------------------------------------------------
    |
    | When true, requests with bodies must have a valid Content-Type header.
    |
    */
    'enforce_content_type' => true,

    /*
    |--------------------------------------------------------------------------
    | Allowed Content-Types
    |--------------------------------------------------------------------------
    |
    | List of allowed Content-Type values for request bodies.
    |
    */
    'allowed_content_types' => [
        'application/json',
        'application/x-www-form-urlencoded',
        'multipart/form-data',
    ],

    /*
    |--------------------------------------------------------------------------
    | Require JSON Content-Type for Paths
    |--------------------------------------------------------------------------
    |
    | Requests matching these path prefixes must use application/json.
    |
    */
    'require_json_paths' => [
        '/api/auth',
        '/api/v1/auth',
    ],

    /*
    |--------------------------------------------------------------------------
    | Enforce Accept Header
    |--------------------------------------------------------------------------
    |
    | When true, validates that the client accepts application/json.
    |
    */
    'enforce_accept_header' => true,

    /*
    |--------------------------------------------------------------------------
    | Validate Headers
    |--------------------------------------------------------------------------
    |
    | Enable/disable header validation.
    |
    */
    'validate_headers' => true,

    /*
    |--------------------------------------------------------------------------
    | Required Headers
    |--------------------------------------------------------------------------
    |
    | Headers that must be present on every request.
    | Note: Authentication headers are handled separately.
    | Note: Trace headers (X-Correlation-Id, X-Transaction-Id, X-Request-Id)
    |       are auto-generated by TraceContext if not provided by client.
    |
    */
    'required_headers' => [
        // Trace headers are auto-generated if missing - don't require them
        // 'X-Correlation-Id',
        // 'X-Transaction-Id', 
        // 'X-Request-Id',
    ],

    /*
    |--------------------------------------------------------------------------
    | Header Validation Rules
    |--------------------------------------------------------------------------
    |
    | Format validation for specific headers when present.
    |
    */
    'header_rules' => [
        'X-Correlation-Id' => [
            'max' => 36,
        ],
        'X-Transaction-Id' => [
            'max' => 36,
        ],
        'X-Request-Id' => [
            'max' => 36,
        ],
        'Authorization' => [
            'pattern' => '/^Bearer\s+[\w\-\.]+$/',
        ],
        'Accept' => [
            'pattern' => '/(^|,)\s*(application\/json|\*\/\*|application\/\*)(\s*;\s*q=[0-9.]+)?\s*(,|$)/i',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Maximum Header Length
    |--------------------------------------------------------------------------
    |
    | Maximum length for any single header value.
    |
    */
    'max_header_length' => 8192,

    /*
    |--------------------------------------------------------------------------
    | Validate Query Parameters
    |--------------------------------------------------------------------------
    |
    | Enable/disable query parameter validation.
    |
    */
    'validate_query_params' => true,

    /*
    |--------------------------------------------------------------------------
    | Maximum Query Parameter Length
    |--------------------------------------------------------------------------
    |
    | Maximum length for any single query parameter value.
    |
    */
    'max_query_param_length' => 1000,

    /*
    |--------------------------------------------------------------------------
    | Maximum Query Parameters
    |--------------------------------------------------------------------------
    |
    | Maximum number of query parameters allowed per request.
    |
    */
    'max_query_params' => 50,

    /*
    |--------------------------------------------------------------------------
    | Allowed HTTP Methods
    |--------------------------------------------------------------------------
    |
    | List of allowed HTTP methods.
    |
    */
    'allowed_methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD'],

    /*
    |--------------------------------------------------------------------------
    | Common Validation Patterns
    |--------------------------------------------------------------------------
    |
    | Reusable patterns for field validation.
    |
    */
    'patterns' => [
        'uuid' => '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i',
        'ulid' => '/^[0-9A-HJKMNP-TV-Z]{26}$/i',
        'email' => '/^[^\s@]+@[^\s@]+\.[^\s@]+$/',
        'phone' => '/^\+?[1-9]\d{1,14}$/',
        'slug' => '/^[a-z0-9]+(?:-[a-z0-9]+)*$/',
        'username' => '/^[a-zA-Z][a-zA-Z0-9_]{2,29}$/',
    ],

    /*
    |--------------------------------------------------------------------------
    | Dangerous Pattern Detection
    |--------------------------------------------------------------------------
    |
    | Enable detection of potentially dangerous input patterns.
    |
    */
    'detect_dangerous_patterns' => true,

    /*
    |--------------------------------------------------------------------------
    | Blocked Input Patterns
    |--------------------------------------------------------------------------
    |
    | Patterns that will cause immediate request rejection.
    |
    */
    'blocked_patterns' => [
        // SQL injection
        '/(\bunion\b.*\bselect\b)/i',
        '/(\bselect\b.*\bfrom\b.*\bwhere\b)/i',
        '/(\bdrop\b.*\btable\b)/i',
        '/(\bdelete\b.*\bfrom\b)/i',
        
        // Script injection
        '/<script[^>]*>/i',
        '/javascript:/i',
        
        // Path traversal
        '/\.\.\//',
        '/\.\.\\\\/',
        
        // Null bytes
        '/\x00/',
    ],
];
